### ISSUE TITLE
Fouriertransformation

### ISSUE THREAD

**Issue by pointan** [FHOOEAIST/imaging#4]
Integrate fourier and inverse fourier transformation.
https://github.com/wuchubuzai/OpenIMAJ/blob/master/image/image-processing/src/main/java/org/openimaj/image/processing/algorithm/FourierTransform.java

Migrated from: https://aist.fh-hagenberg.at/git/Development/imaging/-/issues/289

**Comment by cpraschl** [comment]
Since we have now OpenIMAJ support not required anymore.
