### ISSUE TITLE
Mesh Module

### ISSUE THREAD

**Issue by pointan** [FHOOEAIST/imaging#5]
Add a new module for mesh processing containing:

- Mesh file reader/writer (stl, ply, obj, off)
- Triangulation (Constrained Delaunay, ...)

Migrated from: https://aist.fh-hagenberg.at/git/Development/imaging/-/issues/290

**Comment by cpraschl** [comment]
Maybe use https://github.com/orbisgis/poly2tri.java for triangulation

**Comment by cpraschl** [comment]
Already merged.
