### ISSUE TITLE
ImageJ Module

### ISSUE THREAD

**Issue by pointan** [FHOOEAIST/imaging#6]
Add a new module that is a connector between Imaging and ImageJ.

Migrated from: https://aist.fh-hagenberg.at/git/Development/imaging/-/issues/291

**Comment by cpraschl** [comment]
```xml
<dependency>
  <groupId>net.imagej</groupId>
  <artifactId>imagej</artifactId>
  <version>16.2.0</version>
</dependency>
```

https://github.com/imagej/imagej

But required to configure additional maven repository.
```xml
  <repositories>
    <repository>
      <id>scijava</id>
      <name>Sci Java Repository</name>
      <url>https://maven.scijava.org/</url>
    </repository>
  </repositories>
```
https://maven.apache.org/guides/mini/guide-multiple-repositories.html
